databases:
  - name: shumituketA_DB
    databaseName: shumituketa_db
    user: shumituketA
    region: singapore

services:
  - type: web
    name: shumituketA
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shumituketA_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

